name: vidmore 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel \
          build-essential git zip unzip openjdk-17-jdk wget

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install Cython virtualenv buildozer

    - name: Install Android SDK & NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "platforms;android-31" "platform-tools" "build-tools;31.0.0" "ndk;21.4.7075529"

    - name: Build APK
      run: |
        export ANDROIDSDK=$HOME/android-sdk
        export ANDROIDNDK=$ANDROIDSDK/ndk/21.4.7075529
        export PATH=$ANDROIDSDK/platform-tools:$PATH
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
