name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-11-jdk \
            autoconf automake pkg-config libffi-dev libssl-dev \
            libsqlite3-dev libjpeg-dev libpng-dev

          pip install --upgrade pip
          pip install cython buildozer

      - name: Build AAB
        run: |
          buildozer -v android release

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Vidmore-AAB
          path: bin/*.aab
